version: '3.2'

services:
   db:
     image: registry.adinusa.id/btacademy/mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: yuanpass
       MYSQL_DATABASE: wordpress
       MYSQL_USER: yuan
       MYSQL_PASSWORD: yuan1140

   wordpress:
     depends_on:
       - db
     image: registry.adinusa.id/btacademy/wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: yuan
       WORDPRESS_DB_PASSWORD: yuan1140
volumes:
    dbdata:
